import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";
import Providers from "./components/hooks/providers";
import { CookiesProvider } from 'next-client-cookies/server';
import { Analytics } from "@vercel/analytics/react"

const inter = Inter({
  weight: ["400"],
  subsets: ['latin'],
  variable: '--font-inter'
})

export const metadata: Metadata = {
  title: "Nike. Just Do It, Nike IN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CookiesProvider>
        <Providers>
        <body
          className={`${inter.variable} w-full`}
        >
          {children}
        <Analytics/>
        </body>
        </Providers>
      </CookiesProvider>
    </html>
  );
}
