import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";
import Navbar from "./components/ui/navbar/navbar";
import Footer from "./components/ui/footer/footer";

const inter = Inter({
  weight: ["400"],
  subsets: ['latin'],
  variable: '--font-inter'
})

export const metadata: Metadata = {
  title: "Nike. Just Do It, Nike IN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} w-full`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
